name: NASA Project CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: unbutu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build --prefix client